plugins {
    id 'com.android.application'
}

android {
    namespace 'com.juanjurado.juegosonline'
    compileSdk 35

    defaultConfig {
        applicationId 'com.juanjurado.juegosonline'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '0.1-beta'
    }
}

dependencies {
    implementation 'com.google.android.gms:play-services-ads:24.7.0'
}